{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOX/CzcIhwfCzUYcHD7ugxU",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/pantene-ay/IMG_TEST/blob/main/IMG_A.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 31,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "DGe5X5Y2Swcw",
        "outputId": "7dc562d4-3656-4796-b462-edf7393a50ab"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "インポートが完了しました\n"
          ]
        }
      ],
      "source": [
        "# この題材で使うライブラリをインポートしましょう\n",
        "from IPython.display import clear_output\n",
        "\n",
        "# streamlitのインストールとインポート\n",
        "!pip install streamlit\n",
        "!pip install icrawler\n",
        "clear_output()\n",
        "print(\"インポートが完了しました\")"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from google.colab import files\n",
        "files.view(\"/content\")\n",
        "files.view(\"ai_app.py\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 17
        },
        "id": "OuAN1SHoTIXw",
        "outputId": "b36d164c-1d64-4ee8-f279-1f6957838b9e"
      },
      "execution_count": 32,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "\n",
              "      ((filepath) => {{\n",
              "        if (!google.colab.kernel.accessAllowed) {{\n",
              "          return;\n",
              "        }}\n",
              "        google.colab.files.view(filepath);\n",
              "      }})(\"/content\")"
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "\n",
              "      ((filepath) => {{\n",
              "        if (!google.colab.kernel.accessAllowed) {{\n",
              "          return;\n",
              "        }}\n",
              "        google.colab.files.view(filepath);\n",
              "      }})(\"/content/ai_app.py\")"
            ]
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!streamlit run ai_app.py & sleep 3 && npx localtunnel --port 8501"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "rjJmfFguTMpl",
        "outputId": "2727656d-4208-4f59-cd66-2098b8af9d33"
      },
      "execution_count": 33,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\u001b[?25l[..................] / rollbackFailedOptional: verb npm-session 0b64db8d00704f5\u001b[0m\u001b[K\r\n",
            "Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.\n",
            "\u001b[0m\n",
            "\u001b[0m\n",
            "\u001b[34m\u001b[1m  You can now view your Streamlit app in your browser.\u001b[0m\n",
            "\u001b[0m\n",
            "\u001b[34m  Network URL: \u001b[0m\u001b[1mhttp://172.28.0.12:8501\u001b[0m\n",
            "\u001b[34m  External URL: \u001b[0m\u001b[1mhttp://35.193.254.93:8501\u001b[0m\n",
            "\u001b[0m\n",
            "\u001b[K\u001b[?25hnpx: installed 22 in 5.401s\n",
            "your url is: https://some-horses-hammer-35-193-254-93.loca.lt\n",
            "2023-03-29 03:41:39.621 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 565, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/ai_app.py\", line 91, in <module>\n",
            "    st.set_page_config(\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/metrics_util.py\", line 311, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/commands/page_config.py\", line 225, in set_page_config\n",
            "    ctx.enqueue(msg)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/scriptrunner/script_run_context.py\", line 91, in enqueue\n",
            "    raise StreamlitAPIException(\n",
            "streamlit.errors.StreamlitAPIException: `set_page_config()` can only be called once per app, and must be called as the first Streamlit command in your script.\n",
            "\n",
            "For more information refer to the [docs](https://docs.streamlit.io/library/api-reference/utilities/st.set_page_config).\n",
            "2023-03-29 03:42:29.224 start crawling...\n",
            "2023-03-29 03:42:29.225 starting 1 feeder threads...\n",
            "2023-03-29 03:42:29.226 thread feeder-001 exit\n",
            "2023-03-29 03:42:29.226 starting 1 parser threads...\n",
            "2023-03-29 03:42:29.228 starting 1 downloader threads...\n",
            "2023-03-29 03:42:29.617 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 03:42:32.179 image #1\thttps://img.zcool.cn/community/0191855d5669f0a80120695cfefcec.jpg\n",
            "2023-03-29 03:42:33.082 image #2\thttps://img.zcool.cn/community/01ff855d566c01a8012187f4bddeb3.jpg\n",
            "2023-03-29 03:42:34.015 image #3\thttps://img.zcool.cn/community/01ad715d38ffb5a8012187f42e6273.jpg\n",
            "2023-03-29 03:42:38.949 image #4\thttps://pic.3gbizhi.com/2020/1202/20201202042854590.jpg\n",
            "2023-03-29 03:42:40.230 image #5\thttps://img.zcool.cn/community/0145d05d565d36a80120695cb7da64.jpg\n",
            "2023-03-29 03:42:41.167 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 03:42:41.167 thread downloader-001 exit\n",
            "2023-03-29 03:42:41.242 Crawling task done!\n",
            "2023-03-29 03:42:41.953 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 03:42:41.953 thread parser-001 exit\n",
            "2023-03-29 03:43:43.264 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 565, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/ai_app.py\", line 43, in <module>\n",
            "    ans=(\"この画像の癒し度は\"+\"★\"*num_rand)\n",
            "NameError: name 'num_rand' is not defined\n",
            "2023-03-29 03:43:46.426 start crawling...\n",
            "2023-03-29 03:43:46.427 starting 1 feeder threads...\n",
            "2023-03-29 03:43:46.428 thread feeder-001 exit\n",
            "2023-03-29 03:43:46.429 starting 1 parser threads...\n",
            "2023-03-29 03:43:46.431 starting 1 downloader threads...\n",
            "2023-03-29 03:43:46.764 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 03:43:46.789 skip downloading file 000001.jpg\n",
            "2023-03-29 03:43:46.789 skip downloading file 000002.jpg\n",
            "2023-03-29 03:43:46.790 skip downloading file 000003.jpg\n",
            "2023-03-29 03:43:46.790 skip downloading file 000004.jpg\n",
            "2023-03-29 03:43:46.791 skip downloading file 000005.jpg\n",
            "2023-03-29 03:43:49.202 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 03:43:49.202 thread downloader-001 exit\n",
            "2023-03-29 03:43:49.436 Crawling task done!\n",
            "2023-03-29 03:43:49.879 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 03:43:49.879 thread parser-001 exit\n",
            "2023-03-29 03:43:56.480 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 565, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/ai_app.py\", line 43, in <module>\n",
            "    ans=(\"この画像の癒し度は\"+\"★\"*num_rand)\n",
            "NameError: name 'num_rand' is not defined\n",
            "2023-03-29 03:44:51.086 start crawling...\n",
            "2023-03-29 03:44:51.087 starting 1 feeder threads...\n",
            "2023-03-29 03:44:51.088 thread feeder-001 exit\n",
            "2023-03-29 03:44:51.088 starting 1 parser threads...\n",
            "2023-03-29 03:44:51.090 starting 1 downloader threads...\n",
            "2023-03-29 03:44:51.445 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 03:44:51.469 skip downloading file 000001.jpg\n",
            "2023-03-29 03:44:51.470 skip downloading file 000002.jpg\n",
            "2023-03-29 03:44:51.470 skip downloading file 000003.jpg\n",
            "2023-03-29 03:44:51.470 skip downloading file 000004.jpg\n",
            "2023-03-29 03:44:51.470 skip downloading file 000005.jpg\n",
            "2023-03-29 03:44:57.201 Exception caught when downloading file https://img.zcool.cn/community/0145d05d565d36a80120695cb7da64.jpg, error: HTTPSConnectionPool(host='img.zcool.cn', port=443): Read timed out. (read timeout=5), remaining retry times: 2\n",
            "2023-03-29 03:45:02.540 Exception caught when downloading file https://img.zcool.cn/community/0145d05d565d36a80120695cb7da64.jpg, error: HTTPSConnectionPool(host='img.zcool.cn', port=443): Read timed out. (read timeout=5), remaining retry times: 1\n",
            "2023-03-29 03:45:07.751 Exception caught when downloading file https://img.zcool.cn/community/0145d05d565d36a80120695cb7da64.jpg, error: HTTPSConnectionPool(host='img.zcool.cn', port=443): Read timed out. (read timeout=5), remaining retry times: 0\n",
            "2023-03-29 03:45:12.856 Exception caught when downloading file http://pic23.nipic.com/20120918/6484455_220152616000_2.jpg, error: HTTPConnectionPool(host='pic23.nipic.com', port=80): Max retries exceeded with url: /20120918/6484455_220152616000_2.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feb2c2bf5b0>, 'Connection to pic23.nipic.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
            "2023-03-29 03:45:17.866 Exception caught when downloading file http://pic23.nipic.com/20120918/6484455_220152616000_2.jpg, error: HTTPConnectionPool(host='pic23.nipic.com', port=80): Max retries exceeded with url: /20120918/6484455_220152616000_2.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feb2c2bfb20>, 'Connection to pic23.nipic.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
            "2023-03-29 03:45:22.874 Exception caught when downloading file http://pic23.nipic.com/20120918/6484455_220152616000_2.jpg, error: HTTPConnectionPool(host='pic23.nipic.com', port=80): Max retries exceeded with url: /20120918/6484455_220152616000_2.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feb2c2bff10>, 'Connection to pic23.nipic.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
            "2023-03-29 03:45:23.233 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 03:45:23.233 thread downloader-001 exit\n",
            "2023-03-29 03:45:23.766 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 03:45:23.766 thread parser-001 exit\n",
            "2023-03-29 03:45:24.126 Crawling task done!\n",
            "2023-03-29 03:47:24.858 start crawling...\n",
            "2023-03-29 03:47:24.858 starting 1 feeder threads...\n",
            "2023-03-29 03:47:24.859 thread feeder-001 exit\n",
            "2023-03-29 03:47:24.860 starting 1 parser threads...\n",
            "2023-03-29 03:47:24.861 starting 1 downloader threads...\n",
            "2023-03-29 03:47:25.193 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 03:47:25.221 skip downloading file 000001.jpg\n",
            "2023-03-29 03:47:25.221 skip downloading file 000002.jpg\n",
            "2023-03-29 03:47:25.221 skip downloading file 000003.jpg\n",
            "2023-03-29 03:47:25.221 skip downloading file 000004.jpg\n",
            "2023-03-29 03:47:25.222 skip downloading file 000005.jpg\n",
            "2023-03-29 03:47:27.810 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 03:47:27.810 thread downloader-001 exit\n",
            "2023-03-29 03:47:27.867 Crawling task done!\n",
            "2023-03-29 03:47:27.867 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/state/session_state.py\", line 368, in __getitem__\n",
            "    return self._getitem(widget_id, key)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/state/session_state.py\", line 413, in _getitem\n",
            "    raise KeyError\n",
            "KeyError\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/state/session_state_proxy.py\", line 119, in __getattr__\n",
            "    return self[key]\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/state/session_state_proxy.py\", line 90, in __getitem__\n",
            "    return get_session_state()[key]\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/state/safe_session_state.py\", line 106, in __getitem__\n",
            "    return self._state[key]\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/state/session_state.py\", line 370, in __getitem__\n",
            "    raise KeyError(_missing_key_error_message(key))\n",
            "KeyError: 'st.session_state has no key \"num_rand\". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 565, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/ai_app.py\", line 33, in <module>\n",
            "    st.session_state.num_rand\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/state/session_state_proxy.py\", line 121, in __getattr__\n",
            "    raise AttributeError(_missing_attr_error_message(key))\n",
            "AttributeError: st.session_state has no attribute \"num_rand\". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization\n",
            "2023-03-29 03:47:28.225 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 03:47:28.225 thread parser-001 exit\n",
            "2023-03-29 03:47:50.667 start crawling...\n",
            "2023-03-29 03:47:50.667 starting 1 feeder threads...\n",
            "2023-03-29 03:47:50.668 thread feeder-001 exit\n",
            "2023-03-29 03:47:50.668 starting 1 parser threads...\n",
            "2023-03-29 03:47:50.669 starting 1 downloader threads...\n",
            "2023-03-29 03:47:50.965 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 03:47:50.994 skip downloading file 000001.jpg\n",
            "2023-03-29 03:47:50.994 skip downloading file 000002.jpg\n",
            "2023-03-29 03:47:50.994 skip downloading file 000003.jpg\n",
            "2023-03-29 03:47:50.995 skip downloading file 000004.jpg\n",
            "2023-03-29 03:47:50.995 skip downloading file 000005.jpg\n",
            "2023-03-29 03:47:53.565 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 03:47:53.565 thread downloader-001 exit\n",
            "2023-03-29 03:47:53.674 Crawling task done!\n",
            "2023-03-29 03:47:54.159 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 03:47:54.160 thread parser-001 exit\n",
            "2023-03-29 03:47:56.765 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 565, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/ai_app.py\", line 44, in <module>\n",
            "    ans=(\"この画像の癒し度は\"+\"★\"*num)\n",
            "TypeError: can't multiply sequence by non-int of type 'str'\n",
            "2023-03-29 03:48:32.158 start crawling...\n",
            "2023-03-29 03:48:32.160 starting 1 feeder threads...\n",
            "2023-03-29 03:48:32.160 thread feeder-001 exit\n",
            "2023-03-29 03:48:32.160 starting 1 parser threads...\n",
            "2023-03-29 03:48:32.161 starting 1 downloader threads...\n",
            "2023-03-29 03:48:32.477 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 03:48:32.525 skip downloading file 000001.jpg\n",
            "2023-03-29 03:48:32.526 skip downloading file 000002.jpg\n",
            "2023-03-29 03:48:32.527 skip downloading file 000003.jpg\n",
            "2023-03-29 03:48:32.527 skip downloading file 000004.jpg\n",
            "2023-03-29 03:48:32.527 skip downloading file 000005.jpg\n",
            "2023-03-29 03:48:43.270 Exception caught when downloading file https://img.zcool.cn/community/018f545d392c07a80120695ce88831.jpg, error: HTTPSConnectionPool(host='img.zcool.cn', port=443): Read timed out. (read timeout=5), remaining retry times: 2\n",
            "2023-03-29 03:48:45.841 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 03:48:45.841 thread downloader-001 exit\n",
            "2023-03-29 03:48:46.180 Crawling task done!\n",
            "2023-03-29 03:48:46.615 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 03:48:46.615 thread parser-001 exit\n",
            "2023-03-29 03:51:41.819 start crawling...\n",
            "2023-03-29 03:51:41.819 starting 1 feeder threads...\n",
            "2023-03-29 03:51:41.820 thread feeder-001 exit\n",
            "2023-03-29 03:51:41.820 starting 1 parser threads...\n",
            "2023-03-29 03:51:41.822 starting 1 downloader threads...\n",
            "2023-03-29 03:51:42.151 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 03:51:42.176 skip downloading file 000001.jpg\n",
            "2023-03-29 03:51:42.177 skip downloading file 000002.jpg\n",
            "2023-03-29 03:51:42.177 skip downloading file 000003.jpg\n",
            "2023-03-29 03:51:42.178 skip downloading file 000004.jpg\n",
            "2023-03-29 03:51:42.178 skip downloading file 000005.jpg\n",
            "2023-03-29 03:51:45.242 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 03:51:45.242 thread downloader-001 exit\n",
            "2023-03-29 03:51:45.828 Crawling task done!\n",
            "2023-03-29 03:51:46.182 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 03:51:46.182 thread parser-001 exit\n",
            "2023-03-29 03:51:46.216 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 565, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/ai_app.py\", line 83, in <module>\n",
            "    inputs = transform(img_).reshape(1,3,64,64)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py\", line 95, in __call__\n",
            "    img = t(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py\", line 1194, in _call_impl\n",
            "    return forward_call(*input, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py\", line 346, in forward\n",
            "    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional.py\", line 462, in resize\n",
            "    _, image_height, image_width = get_dimensions(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional.py\", line 75, in get_dimensions\n",
            "    return F_pil.get_dimensions(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional_pil.py\", line 33, in get_dimensions\n",
            "    raise TypeError(f\"Unexpected type {type(img)}\")\n",
            "TypeError: Unexpected type <class 'numpy.ndarray'>\n",
            "2023-03-29 03:55:15.522 start crawling...\n",
            "2023-03-29 03:55:15.523 starting 1 feeder threads...\n",
            "2023-03-29 03:55:15.524 thread feeder-001 exit\n",
            "2023-03-29 03:55:15.524 starting 1 parser threads...\n",
            "2023-03-29 03:55:15.526 starting 1 downloader threads...\n",
            "2023-03-29 03:55:15.799 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 03:55:15.824 skip downloading file 000001.jpg\n",
            "2023-03-29 03:55:15.824 skip downloading file 000002.jpg\n",
            "2023-03-29 03:55:15.824 skip downloading file 000003.jpg\n",
            "2023-03-29 03:55:15.825 skip downloading file 000004.jpg\n",
            "2023-03-29 03:55:15.825 skip downloading file 000005.jpg\n",
            "2023-03-29 03:55:20.212 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 03:55:20.212 thread downloader-001 exit\n",
            "2023-03-29 03:55:20.533 Crawling task done!\n",
            "2023-03-29 03:55:20.831 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 03:55:20.831 thread parser-001 exit\n",
            "2023-03-29 03:55:20.923 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 565, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/ai_app.py\", line 83, in <module>\n",
            "    inputs = transform(img_).reshape(1,3,64,64)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py\", line 95, in __call__\n",
            "    img = t(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py\", line 1194, in _call_impl\n",
            "    return forward_call(*input, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py\", line 346, in forward\n",
            "    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional.py\", line 462, in resize\n",
            "    _, image_height, image_width = get_dimensions(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional.py\", line 75, in get_dimensions\n",
            "    return F_pil.get_dimensions(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional_pil.py\", line 33, in get_dimensions\n",
            "    raise TypeError(f\"Unexpected type {type(img)}\")\n",
            "TypeError: Unexpected type <class 'numpy.ndarray'>\n",
            "2023-03-29 03:56:18.672 start crawling...\n",
            "2023-03-29 03:56:18.672 starting 1 feeder threads...\n",
            "2023-03-29 03:56:18.673 thread feeder-001 exit\n",
            "2023-03-29 03:56:18.673 starting 1 parser threads...\n",
            "2023-03-29 03:56:18.675 starting 1 downloader threads...\n",
            "2023-03-29 03:56:18.967 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 03:56:18.992 skip downloading file 000001.jpg\n",
            "2023-03-29 03:56:18.994 skip downloading file 000002.jpg\n",
            "2023-03-29 03:56:18.994 skip downloading file 000003.jpg\n",
            "2023-03-29 03:56:18.995 skip downloading file 000004.jpg\n",
            "2023-03-29 03:56:18.995 skip downloading file 000005.jpg\n",
            "2023-03-29 03:56:24.696 Exception caught when downloading file https://img.zcool.cn/community/018f545d392c07a80120695ce88831.jpg, error: HTTPSConnectionPool(host='img.zcool.cn', port=443): Read timed out. (read timeout=5), remaining retry times: 2\n",
            "2023-03-29 03:56:27.265 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 03:56:27.265 thread downloader-001 exit\n",
            "2023-03-29 03:56:27.686 Crawling task done!\n",
            "2023-03-29 03:56:28.011 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 03:56:28.011 thread parser-001 exit\n",
            "2023-03-29 03:59:04.849 start crawling...\n",
            "2023-03-29 03:59:04.849 starting 1 feeder threads...\n",
            "2023-03-29 03:59:04.849 thread feeder-001 exit\n",
            "2023-03-29 03:59:04.849 starting 1 parser threads...\n",
            "2023-03-29 03:59:04.851 starting 1 downloader threads...\n",
            "2023-03-29 03:59:05.165 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 03:59:05.188 skip downloading file 000001.jpg\n",
            "2023-03-29 03:59:05.189 skip downloading file 000002.jpg\n",
            "2023-03-29 03:59:05.189 skip downloading file 000003.jpg\n",
            "2023-03-29 03:59:05.189 skip downloading file 000004.jpg\n",
            "2023-03-29 03:59:05.190 skip downloading file 000005.jpg\n",
            "2023-03-29 03:59:10.801 Exception caught when downloading file https://img.zcool.cn/community/018f545d392c07a80120695ce88831.jpg, error: HTTPSConnectionPool(host='img.zcool.cn', port=443): Read timed out. (read timeout=5), remaining retry times: 2\n",
            "2023-03-29 03:59:16.013 Exception caught when downloading file https://img.zcool.cn/community/018f545d392c07a80120695ce88831.jpg, error: HTTPSConnectionPool(host='img.zcool.cn', port=443): Read timed out. (read timeout=5), remaining retry times: 1\n",
            "2023-03-29 03:59:21.230 Exception caught when downloading file https://img.zcool.cn/community/018f545d392c07a80120695ce88831.jpg, error: HTTPSConnectionPool(host='img.zcool.cn', port=443): Read timed out. (read timeout=5), remaining retry times: 0\n",
            "2023-03-29 03:59:23.149 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 03:59:23.149 thread downloader-001 exit\n",
            "2023-03-29 03:59:23.232 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 03:59:23.232 thread parser-001 exit\n",
            "2023-03-29 03:59:23.874 Crawling task done!\n",
            "2023-03-29 03:59:24.258 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 565, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/ai_app.py\", line 83, in <module>\n",
            "    inputs = transform(img_).reshape(1,3,64,64)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py\", line 95, in __call__\n",
            "    img = t(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py\", line 1194, in _call_impl\n",
            "    return forward_call(*input, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py\", line 346, in forward\n",
            "    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional.py\", line 462, in resize\n",
            "    _, image_height, image_width = get_dimensions(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional.py\", line 75, in get_dimensions\n",
            "    return F_pil.get_dimensions(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional_pil.py\", line 33, in get_dimensions\n",
            "    raise TypeError(f\"Unexpected type {type(img)}\")\n",
            "TypeError: Unexpected type <class 'numpy.ndarray'>\n",
            "2023-03-29 04:00:12.351 start crawling...\n",
            "2023-03-29 04:00:12.351 starting 1 feeder threads...\n",
            "2023-03-29 04:00:12.351 thread feeder-001 exit\n",
            "2023-03-29 04:00:12.351 starting 1 parser threads...\n",
            "2023-03-29 04:00:12.352 starting 1 downloader threads...\n",
            "2023-03-29 04:00:12.659 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 04:00:12.685 skip downloading file 000001.jpg\n",
            "2023-03-29 04:00:12.687 skip downloading file 000002.jpg\n",
            "2023-03-29 04:00:12.687 skip downloading file 000003.jpg\n",
            "2023-03-29 04:00:12.687 skip downloading file 000004.jpg\n",
            "2023-03-29 04:00:12.688 skip downloading file 000005.jpg\n",
            "2023-03-29 04:00:15.089 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 04:00:15.089 thread downloader-001 exit\n",
            "2023-03-29 04:00:15.357 Crawling task done!\n",
            "2023-03-29 04:00:15.698 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 04:00:15.699 thread parser-001 exit\n",
            "2023-03-29 04:00:15.855 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 565, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/ai_app.py\", line 83, in <module>\n",
            "    inputs = transform(img).reshape(1,3,64,64)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py\", line 95, in __call__\n",
            "    img = t(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py\", line 1194, in _call_impl\n",
            "    return forward_call(*input, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py\", line 346, in forward\n",
            "    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional.py\", line 462, in resize\n",
            "    _, image_height, image_width = get_dimensions(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional.py\", line 75, in get_dimensions\n",
            "    return F_pil.get_dimensions(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional_pil.py\", line 33, in get_dimensions\n",
            "    raise TypeError(f\"Unexpected type {type(img)}\")\n",
            "TypeError: Unexpected type <class 'numpy.ndarray'>\n",
            "2023-03-29 04:05:53.566 start crawling...\n",
            "2023-03-29 04:05:53.566 starting 1 feeder threads...\n",
            "2023-03-29 04:05:53.567 thread feeder-001 exit\n",
            "2023-03-29 04:05:53.567 starting 1 parser threads...\n",
            "2023-03-29 04:05:53.574 starting 1 downloader threads...\n",
            "2023-03-29 04:05:53.871 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 04:05:53.926 skip downloading file 000001.jpg\n",
            "2023-03-29 04:05:53.926 skip downloading file 000002.jpg\n",
            "2023-03-29 04:05:53.926 skip downloading file 000003.jpg\n",
            "2023-03-29 04:05:53.927 skip downloading file 000004.jpg\n",
            "2023-03-29 04:05:53.927 skip downloading file 000005.jpg\n",
            "2023-03-29 04:05:56.992 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 04:05:56.992 thread downloader-001 exit\n",
            "2023-03-29 04:05:57.581 Crawling task done!\n",
            "2023-03-29 04:05:57.933 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 04:05:57.933 thread parser-001 exit\n",
            "2023-03-29 04:05:57.973 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 565, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/ai_app.py\", line 83, in <module>\n",
            "    inputs = transform(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py\", line 95, in __call__\n",
            "    img = t(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py\", line 1194, in _call_impl\n",
            "    return forward_call(*input, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py\", line 346, in forward\n",
            "    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional.py\", line 462, in resize\n",
            "    _, image_height, image_width = get_dimensions(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional.py\", line 75, in get_dimensions\n",
            "    return F_pil.get_dimensions(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional_pil.py\", line 33, in get_dimensions\n",
            "    raise TypeError(f\"Unexpected type {type(img)}\")\n",
            "TypeError: Unexpected type <class 'numpy.ndarray'>\n",
            "2023-03-29 04:07:43.648 start crawling...\n",
            "2023-03-29 04:07:43.649 starting 1 feeder threads...\n",
            "2023-03-29 04:07:43.650 thread feeder-001 exit\n",
            "2023-03-29 04:07:43.650 starting 1 parser threads...\n",
            "2023-03-29 04:07:43.651 starting 1 downloader threads...\n",
            "2023-03-29 04:07:43.954 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 04:07:43.981 skip downloading file 000001.jpg\n",
            "2023-03-29 04:07:43.981 skip downloading file 000002.jpg\n",
            "2023-03-29 04:07:43.981 skip downloading file 000003.jpg\n",
            "2023-03-29 04:07:43.981 skip downloading file 000004.jpg\n",
            "2023-03-29 04:07:43.982 skip downloading file 000005.jpg\n",
            "2023-03-29 04:07:49.659 Exception caught when downloading file https://img.zcool.cn/community/018f545d392c07a80120695ce88831.jpg, error: HTTPSConnectionPool(host='img.zcool.cn', port=443): Read timed out. (read timeout=5), remaining retry times: 2\n",
            "2023-03-29 04:07:54.874 Exception caught when downloading file https://img.zcool.cn/community/018f545d392c07a80120695ce88831.jpg, error: HTTPSConnectionPool(host='img.zcool.cn', port=443): Read timed out. (read timeout=5), remaining retry times: 1\n",
            "2023-03-29 04:08:00.085 Exception caught when downloading file https://img.zcool.cn/community/018f545d392c07a80120695ce88831.jpg, error: HTTPSConnectionPool(host='img.zcool.cn', port=443): Read timed out. (read timeout=5), remaining retry times: 0\n",
            "2023-03-29 04:08:02.433 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 04:08:02.433 thread downloader-001 exit\n",
            "2023-03-29 04:08:02.674 Crawling task done!\n",
            "2023-03-29 04:08:03.089 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 04:08:03.089 thread parser-001 exit\n",
            "2023-03-29 04:08:11.733 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 565, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/ai_app.py\", line 85, in <module>\n",
            "    outputs = cnn_original()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py\", line 1194, in _call_impl\n",
            "    return forward_call(*input, **kwargs)\n",
            "TypeError: forward() missing 1 required positional argument: 'x'\n",
            "2023-03-29 04:14:27.120 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 565, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/ai_app.py\", line 82, in <module>\n",
            "    inputs = transform(img).reshape(1,3,64,64)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py\", line 95, in __call__\n",
            "    img = t(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py\", line 1194, in _call_impl\n",
            "    return forward_call(*input, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py\", line 346, in forward\n",
            "    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional.py\", line 462, in resize\n",
            "    _, image_height, image_width = get_dimensions(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional.py\", line 75, in get_dimensions\n",
            "    return F_pil.get_dimensions(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional_pil.py\", line 33, in get_dimensions\n",
            "    raise TypeError(f\"Unexpected type {type(img)}\")\n",
            "TypeError: Unexpected type <class 'numpy.ndarray'>\n",
            "2023-03-29 04:16:43.114 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 565, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/ai_app.py\", line 82, in <module>\n",
            "    inputs = transform(img).reshape(1,3,64,64)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py\", line 95, in __call__\n",
            "    img = t(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py\", line 1194, in _call_impl\n",
            "    return forward_call(*input, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py\", line 346, in forward\n",
            "    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional.py\", line 462, in resize\n",
            "    _, image_height, image_width = get_dimensions(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional.py\", line 75, in get_dimensions\n",
            "    return F_pil.get_dimensions(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional_pil.py\", line 33, in get_dimensions\n",
            "    raise TypeError(f\"Unexpected type {type(img)}\")\n",
            "TypeError: Unexpected type <class 'numpy.ndarray'>\n",
            "2023-03-29 04:19:41.102 start crawling...\n",
            "2023-03-29 04:19:41.103 starting 1 feeder threads...\n",
            "2023-03-29 04:19:41.104 thread feeder-001 exit\n",
            "2023-03-29 04:19:41.104 starting 1 parser threads...\n",
            "2023-03-29 04:19:41.106 starting 1 downloader threads...\n",
            "2023-03-29 04:19:41.408 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 04:19:41.433 skip downloading file 000001.jpg\n",
            "2023-03-29 04:19:41.437 skip downloading file 000002.jpg\n",
            "2023-03-29 04:19:41.437 skip downloading file 000003.jpg\n",
            "2023-03-29 04:19:41.437 skip downloading file 000004.jpg\n",
            "2023-03-29 04:19:41.438 skip downloading file 000005.jpg\n",
            "2023-03-29 04:19:44.085 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 04:19:44.085 thread downloader-001 exit\n",
            "2023-03-29 04:19:44.112 Crawling task done!\n",
            "2023-03-29 04:19:44.562 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 04:19:44.562 thread parser-001 exit\n",
            "2023-03-29 04:19:46.678 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 565, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/ai_app.py\", line 85, in <module>\n",
            "    outputs = cnn_original(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py\", line 1194, in _call_impl\n",
            "    return forward_call(*input, **kwargs)\n",
            "  File \"/content/ai_app.py\", line 37, in forward\n",
            "    h = self.conv1(x)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py\", line 1194, in _call_impl\n",
            "    return forward_call(*input, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torch/nn/modules/conv.py\", line 463, in forward\n",
            "    return self._conv_forward(input, self.weight, self.bias)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torch/nn/modules/conv.py\", line 459, in _conv_forward\n",
            "    return F.conv2d(input, weight, bias, self.stride,\n",
            "TypeError: conv2d() received an invalid combination of arguments - got (numpy.ndarray, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:\n",
            " * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)\n",
            "      didn't match because some of the arguments have invalid types: (\u001b[31;1mnumpy.ndarray\u001b[0m, \u001b[31;1mParameter\u001b[0m, \u001b[31;1mParameter\u001b[0m, \u001b[31;1mtuple\u001b[0m, \u001b[31;1mtuple\u001b[0m, \u001b[31;1mtuple\u001b[0m, \u001b[32;1mint\u001b[0m)\n",
            " * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)\n",
            "      didn't match because some of the arguments have invalid types: (\u001b[31;1mnumpy.ndarray\u001b[0m, \u001b[31;1mParameter\u001b[0m, \u001b[31;1mParameter\u001b[0m, \u001b[31;1mtuple\u001b[0m, \u001b[31;1mtuple\u001b[0m, \u001b[31;1mtuple\u001b[0m, \u001b[32;1mint\u001b[0m)\n",
            "\n",
            "2023-03-29 04:21:03.153 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 565, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/ai_app.py\", line 82, in <module>\n",
            "    inputs=transform(img).reshape(1,3,64,64)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py\", line 95, in __call__\n",
            "    img = t(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py\", line 1194, in _call_impl\n",
            "    return forward_call(*input, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py\", line 346, in forward\n",
            "    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional.py\", line 462, in resize\n",
            "    _, image_height, image_width = get_dimensions(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional.py\", line 75, in get_dimensions\n",
            "    return F_pil.get_dimensions(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional_pil.py\", line 33, in get_dimensions\n",
            "    raise TypeError(f\"Unexpected type {type(img)}\")\n",
            "TypeError: Unexpected type <class 'numpy.ndarray'>\n",
            "2023-03-29 04:23:56.194 start crawling...\n",
            "2023-03-29 04:23:56.194 starting 1 feeder threads...\n",
            "2023-03-29 04:23:56.196 thread feeder-001 exit\n",
            "2023-03-29 04:23:56.196 starting 1 parser threads...\n",
            "2023-03-29 04:23:56.199 starting 1 downloader threads...\n",
            "2023-03-29 04:23:56.475 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 04:23:56.500 skip downloading file 000001.jpg\n",
            "2023-03-29 04:23:56.500 skip downloading file 000002.jpg\n",
            "2023-03-29 04:23:56.501 skip downloading file 000003.jpg\n",
            "2023-03-29 04:23:56.501 skip downloading file 000004.jpg\n",
            "2023-03-29 04:23:56.501 skip downloading file 000005.jpg\n",
            "2023-03-29 04:23:59.878 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 04:23:59.878 thread downloader-001 exit\n",
            "2023-03-29 04:24:00.206 Crawling task done!\n",
            "2023-03-29 04:24:00.410 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 565, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/ai_app.py\", line 82, in <module>\n",
            "    inputs=transform(img).reshape(1,3,64,64)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py\", line 95, in __call__\n",
            "    img = t(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py\", line 1194, in _call_impl\n",
            "    return forward_call(*input, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py\", line 346, in forward\n",
            "    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional.py\", line 462, in resize\n",
            "    _, image_height, image_width = get_dimensions(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional.py\", line 75, in get_dimensions\n",
            "    return F_pil.get_dimensions(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional_pil.py\", line 33, in get_dimensions\n",
            "    raise TypeError(f\"Unexpected type {type(img)}\")\n",
            "TypeError: Unexpected type <class 'numpy.ndarray'>\n",
            "2023-03-29 04:24:00.612 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 04:24:00.612 thread parser-001 exit\n",
            "2023-03-29 04:28:01.500 start crawling...\n",
            "2023-03-29 04:28:01.500 starting 1 feeder threads...\n",
            "2023-03-29 04:28:01.500 thread feeder-001 exit\n",
            "2023-03-29 04:28:01.501 starting 1 parser threads...\n",
            "2023-03-29 04:28:01.502 starting 1 downloader threads...\n",
            "2023-03-29 04:28:01.858 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 04:28:01.902 skip downloading file 000001.jpg\n",
            "2023-03-29 04:28:01.903 skip downloading file 000002.jpg\n",
            "2023-03-29 04:28:01.904 skip downloading file 000003.jpg\n",
            "2023-03-29 04:28:01.904 skip downloading file 000004.jpg\n",
            "2023-03-29 04:28:01.904 skip downloading file 000005.jpg\n",
            "2023-03-29 04:28:05.039 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 04:28:05.039 thread downloader-001 exit\n",
            "2023-03-29 04:28:05.508 Crawling task done!\n",
            "2023-03-29 04:28:05.909 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 04:28:05.910 thread parser-001 exit\n",
            "2023-03-29 04:28:05.910 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 565, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/ai_app.py\", line 84, in <module>\n",
            "    print(f'img.format: {img.format}')  # img.format: JPEG\n",
            "AttributeError: 'numpy.ndarray' object has no attribute 'format'\n",
            "2023-03-29 04:29:02.429 start crawling...\n",
            "2023-03-29 04:29:02.429 starting 1 feeder threads...\n",
            "2023-03-29 04:29:02.430 thread feeder-001 exit\n",
            "2023-03-29 04:29:02.430 starting 1 parser threads...\n",
            "2023-03-29 04:29:02.432 starting 1 downloader threads...\n",
            "2023-03-29 04:29:02.734 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 04:29:02.758 skip downloading file 000001.jpg\n",
            "2023-03-29 04:29:02.759 skip downloading file 000002.jpg\n",
            "2023-03-29 04:29:02.760 skip downloading file 000003.jpg\n",
            "2023-03-29 04:29:02.760 skip downloading file 000004.jpg\n",
            "2023-03-29 04:29:02.760 skip downloading file 000005.jpg\n",
            "2023-03-29 04:29:08.474 Exception caught when downloading file https://img.zcool.cn/community/018f545d392c07a80120695ce88831.jpg, error: HTTPSConnectionPool(host='img.zcool.cn', port=443): Read timed out. (read timeout=5), remaining retry times: 2\n",
            "2023-03-29 04:29:11.199 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 04:29:11.199 thread downloader-001 exit\n",
            "2023-03-29 04:29:11.444 Crawling task done!\n",
            "2023-03-29 04:29:11.768 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 04:29:11.769 thread parser-001 exit\n",
            "2023-03-29 04:29:11.825 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 565, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/ai_app.py\", line 82, in <module>\n",
            "    inputs=transform(img).reshape(1,3,64,64)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py\", line 95, in __call__\n",
            "    img = t(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py\", line 1194, in _call_impl\n",
            "    return forward_call(*input, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py\", line 346, in forward\n",
            "    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional.py\", line 462, in resize\n",
            "    _, image_height, image_width = get_dimensions(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional.py\", line 75, in get_dimensions\n",
            "    return F_pil.get_dimensions(img)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional_pil.py\", line 33, in get_dimensions\n",
            "    raise TypeError(f\"Unexpected type {type(img)}\")\n",
            "TypeError: Unexpected type <class 'numpy.ndarray'>\n",
            "2023-03-29 04:29:24.506 start crawling...\n",
            "2023-03-29 04:29:24.506 starting 1 feeder threads...\n",
            "2023-03-29 04:29:24.507 thread feeder-001 exit\n",
            "2023-03-29 04:29:24.507 starting 1 parser threads...\n",
            "2023-03-29 04:29:24.509 starting 1 downloader threads...\n",
            "2023-03-29 04:29:24.773 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 04:29:24.800 skip downloading file 000001.jpg\n",
            "2023-03-29 04:29:24.800 skip downloading file 000002.jpg\n",
            "2023-03-29 04:29:24.800 skip downloading file 000003.jpg\n",
            "2023-03-29 04:29:24.800 skip downloading file 000004.jpg\n",
            "2023-03-29 04:29:24.800 skip downloading file 000005.jpg\n",
            "2023-03-29 04:29:27.095 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 04:29:27.095 thread downloader-001 exit\n",
            "2023-03-29 04:29:27.515 Crawling task done!\n",
            "2023-03-29 04:29:27.911 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 04:29:27.911 thread parser-001 exit\n",
            "2023-03-29 04:30:28.992 start crawling...\n",
            "2023-03-29 04:30:28.992 starting 1 feeder threads...\n",
            "2023-03-29 04:30:28.993 thread feeder-001 exit\n",
            "2023-03-29 04:30:28.993 starting 1 parser threads...\n",
            "2023-03-29 04:30:28.995 starting 1 downloader threads...\n",
            "2023-03-29 04:30:29.269 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 04:30:29.292 skip downloading file 000001.jpg\n",
            "2023-03-29 04:30:29.294 skip downloading file 000002.jpg\n",
            "2023-03-29 04:30:29.294 skip downloading file 000003.jpg\n",
            "2023-03-29 04:30:29.294 skip downloading file 000004.jpg\n",
            "2023-03-29 04:30:29.295 skip downloading file 000005.jpg\n",
            "2023-03-29 04:30:32.347 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 04:30:32.347 thread downloader-001 exit\n",
            "2023-03-29 04:30:33.000 Crawling task done!\n",
            "2023-03-29 04:30:33.306 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 04:30:33.315 thread parser-001 exit\n",
            "2023-03-29 04:30:39.445 start crawling...\n",
            "2023-03-29 04:30:39.445 starting 1 feeder threads...\n",
            "2023-03-29 04:30:39.446 thread feeder-001 exit\n",
            "2023-03-29 04:30:39.446 starting 1 parser threads...\n",
            "2023-03-29 04:30:39.448 starting 1 downloader threads...\n",
            "2023-03-29 04:30:39.732 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 04:30:39.757 skip downloading file 000001.jpg\n",
            "2023-03-29 04:30:39.758 skip downloading file 000002.jpg\n",
            "2023-03-29 04:30:39.758 skip downloading file 000003.jpg\n",
            "2023-03-29 04:30:39.758 skip downloading file 000004.jpg\n",
            "2023-03-29 04:30:39.758 skip downloading file 000005.jpg\n",
            "2023-03-29 04:30:41.919 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 04:30:41.919 thread downloader-001 exit\n",
            "2023-03-29 04:30:42.453 Crawling task done!\n",
            "2023-03-29 04:30:42.772 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 04:30:42.772 thread parser-001 exit\n",
            "2023-03-29 04:30:50.904 start crawling...\n",
            "2023-03-29 04:30:50.905 starting 1 feeder threads...\n",
            "2023-03-29 04:30:50.906 thread feeder-001 exit\n",
            "2023-03-29 04:30:50.906 starting 1 parser threads...\n",
            "2023-03-29 04:30:50.907 starting 1 downloader threads...\n",
            "2023-03-29 04:30:51.210 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 04:30:51.254 skip downloading file 000001.jpg\n",
            "2023-03-29 04:30:51.254 skip downloading file 000002.jpg\n",
            "2023-03-29 04:30:51.254 skip downloading file 000003.jpg\n",
            "2023-03-29 04:30:51.254 skip downloading file 000004.jpg\n",
            "2023-03-29 04:30:51.254 skip downloading file 000005.jpg\n",
            "2023-03-29 04:30:54.047 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 04:30:54.047 thread downloader-001 exit\n",
            "2023-03-29 04:30:54.915 Crawling task done!\n",
            "2023-03-29 04:30:55.264 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 04:30:55.265 thread parser-001 exit\n",
            "2023-03-29 04:31:00.102 start crawling...\n",
            "2023-03-29 04:31:00.102 starting 1 feeder threads...\n",
            "2023-03-29 04:31:00.103 thread feeder-001 exit\n",
            "2023-03-29 04:31:00.103 starting 1 parser threads...\n",
            "2023-03-29 04:31:00.105 starting 1 downloader threads...\n",
            "2023-03-29 04:31:00.493 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 04:31:00.520 skip downloading file 000001.jpg\n",
            "2023-03-29 04:31:00.520 skip downloading file 000002.jpg\n",
            "2023-03-29 04:31:00.520 skip downloading file 000003.jpg\n",
            "2023-03-29 04:31:00.521 skip downloading file 000004.jpg\n",
            "2023-03-29 04:31:00.521 skip downloading file 000005.jpg\n",
            "2023-03-29 04:31:05.396 start crawling...\n",
            "2023-03-29 04:31:05.396 starting 1 feeder threads...\n",
            "2023-03-29 04:31:05.397 thread feeder-001 exit\n",
            "2023-03-29 04:31:05.397 starting 1 parser threads...\n",
            "2023-03-29 04:31:05.399 starting 1 downloader threads...\n",
            "2023-03-29 04:31:05.673 parsing result page https://www.bing.com/images/async?q=猫&first=0\n",
            "2023-03-29 04:31:05.699 skip downloading file 000001.jpg\n",
            "2023-03-29 04:31:05.699 skip downloading file 000002.jpg\n",
            "2023-03-29 04:31:05.700 skip downloading file 000003.jpg\n",
            "2023-03-29 04:31:05.700 skip downloading file 000004.jpg\n",
            "2023-03-29 04:31:05.700 skip downloading file 000005.jpg\n",
            "2023-03-29 04:31:06.307 Exception caught when downloading file https://img.zcool.cn/community/018f545d392c07a80120695ce88831.jpg, error: HTTPSConnectionPool(host='img.zcool.cn', port=443): Read timed out. (read timeout=5), remaining retry times: 2\n",
            "2023-03-29 04:31:10.953 Exception caught when downloading file https://img.zcool.cn/community/0145d05d565d36a80120695cb7da64.jpg, error: HTTPSConnectionPool(host='img.zcool.cn', port=443): Read timed out. (read timeout=5), remaining retry times: 2\n",
            "2023-03-29 04:31:11.558 Exception caught when downloading file https://img.zcool.cn/community/018f545d392c07a80120695ce88831.jpg, error: HTTPSConnectionPool(host='img.zcool.cn', port=443): Read timed out. (read timeout=5), remaining retry times: 1\n",
            "2023-03-29 04:31:13.591 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 04:31:13.591 thread downloader-001 exit\n",
            "2023-03-29 04:31:13.696 downloaded images reach max num, thread downloader-001 is ready to exit\n",
            "2023-03-29 04:31:13.696 thread downloader-001 exit\n",
            "2023-03-29 04:31:13.708 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 04:31:13.708 thread parser-001 exit\n",
            "2023-03-29 04:31:14.121 Crawling task done!\n",
            "2023-03-29 04:31:14.208 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/state/session_state_proxy.py\", line 119, in __getattr__\n",
            "    return self[key]\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/state/session_state_proxy.py\", line 90, in __getitem__\n",
            "    return get_session_state()[key]\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/state/safe_session_state.py\", line 104, in __getitem__\n",
            "    raise KeyError(key)\n",
            "KeyError: 'img_'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 565, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/ai_app.py\", line 35, in <module>\n",
            "    if st.session_state.img_ is not None:\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/streamlit/runtime/state/session_state_proxy.py\", line 121, in __getattr__\n",
            "    raise AttributeError(_missing_attr_error_message(key))\n",
            "AttributeError: st.session_state has no attribute \"img_\". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization\n",
            "2023-03-29 04:31:14.410 Crawling task done!\n",
            "2023-03-29 04:31:14.532 downloaded image reached max num, thread parser-001 is ready to exit\n",
            "2023-03-29 04:31:14.532 thread parser-001 exit\n",
            "\u001b[34m  Stopping...\u001b[0m\n",
            "^C\n"
          ]
        }
      ]
    }
  ]
}